modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId = "snowmore" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Snow More Mr. Nice Golem" #mandatory
logoFile = "logo.png"
credits = "Commissioned by Vazkii for Bliss" #optional
# A text field displayed in the mod UI
authors = "petrakat" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
A mod for the Bliss modpack that makes it possible to kill the Wither with snow golems.
'''

[[dependencies.snowmore]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.snowmore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snowmore]]
modId = "paucal"
mandatory = true
versionRange = "[0.5.0,0.6.0)"
ordering = "NONE"
side = "BOTH"